name: Filter

on:
 pull_request:
   types:
    - opened
    - Syncronised
   branches:
    - master

jobs:
 echo_filter:
   runs-on: ubuntu-latest
   steps:
     - run: echo "Run whenever there is a open pull request"
